/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View_Thuoc_Tinh;

import Model.XuatXu;
import Repository.XuatXuRepo;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ViewXuatXu extends javax.swing.JPanel {

    private JComboBox<String> cbbXuatXu;
    private XuatXuRepo repoXX = new XuatXuRepo();

    /**
     * Creates new form ViewXuatXu
     */
    public ViewXuatXu(JComboBox<String> cbbXuatXu) {
        this.cbbXuatXu = cbbXuatXu;
        initComponents();
        txtID.setEditable(false);
        loadTable();
    }

    private void loadComboBoxChatLieu() {
        cbbXuatXu.removeAllItems(); // Xóa hết dữ liệu cũ
        List<XuatXu> listXX = repoXX.getAll(); // Lấy danh sách chất liệu từ database

        for (XuatXu xx : listXX) {
            cbbXuatXu.addItem(xx.getTenXX()); // Thêm từng chất liệu vào ComboBox
        }
    }

    public void loadTable() {
        DefaultTableModel mode = (DefaultTableModel) this.tblXuatXu.getModel();
        mode.setRowCount(0);
        List<XuatXu> list = repoXX.getAll();
        for (XuatXu xx : list) {
            Object[] rowData = {
                xx.getId(),
                xx.getTenXX(),};
            mode.addRow(rowData);
        }
    }

    public void loadTableTimXX(String keyword) {
        DefaultTableModel mode = (DefaultTableModel) this.tblXuatXu.getModel();
        mode.setRowCount(0);
        List<XuatXu> list = repoXX.getTimKT(keyword);
        for (XuatXu xx : list) {
            Object[] rowData = {
                xx.getId(),
                xx.getTenXX(),};
            mode.addRow(rowData);
        }
    }

    public void xoaFrom() {
        txtXuatXu.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTimKiemXX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtXuatXu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblXuatXu = new javax.swing.JTable();
        btnThemXX = new javax.swing.JButton();
        btnSuaXX = new javax.swing.JButton();
        btnXoaXX = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();

        jLabel1.setText("Tìm Kiếm");

        jLabel2.setText("Xuất Xứ");

        tblXuatXu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Xuất Xứ", "Xuất Xứ"
            }
        ));
        tblXuatXu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblXuatXuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblXuatXu);

        btnThemXX.setText("Thêm");
        btnThemXX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemXXActionPerformed(evt);
            }
        });

        btnSuaXX.setText("Sửa");
        btnSuaXX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaXXActionPerformed(evt);
            }
        });

        btnXoaXX.setText("Xóa");
        btnXoaXX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaXXActionPerformed(evt);
            }
        });

        jLabel3.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTimKiemXX, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtXuatXu, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(txtID))))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThemXX)
                                .addGap(18, 18, 18)
                                .addComponent(btnSuaXX))
                            .addComponent(btnXoaXX))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTimKiemXX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemXX)
                    .addComponent(btnSuaXX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaXX))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemXXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemXXActionPerformed
       try {
            String tenXX = txtXuatXu.getText().trim();

            // Kiểm tra rỗng
            if (tenXX.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
                return;
            }

            // Kiểm tra khoảng trắng liên tục
            if (tenXX.matches(".*\\s{2,}.*")) { // Kiểm tra nếu có 2 khoảng trắng liên tiếp
                JOptionPane.showMessageDialog(this, "Tên không được chứa khoảng trắng liên tục.");
                return;
            }

            // Kiểm tra có chứa số không
            if (tenXX.matches(".*\\d.*")) {
                JOptionPane.showMessageDialog(this, "Tên không được chứa số.");
                return;
            }

            // Kiểm tra ký tự đặc biệt (chỉ cho phép chữ cái + dấu cách)
            if (!tenXX.matches("^[a-zA-ZàáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđÀÁẠẢÃÂẦẤẬẨẪĂẰẮẶẲẴÈÉẸẺẼÊỀẾỆỂỄÌÍỊỈĨÒÓỌỎÕÔỒỐỘỔỖƠỜỚỢỞỠÙÚỤỦŨƯỪỨỰỬỮỲÝỴỶỸĐ ]+$")) {
                JOptionPane.showMessageDialog(this, "Tên không được chứa ký tự đặc biệt.");
                return;
            }
            if(repoXX.checkTrung(tenXX)){
                JOptionPane.showMessageDialog(this, "Xuất Xứ đã tồn tại");
                return;
            }

            // Tạo đối tượng ChatLieu và thêm vào DB
            XuatXu xx = new XuatXu(tenXX);
            repoXX.add(xx); // Giả sử repoCL là lớp xử lý database           
            loadTable();  // Cập nhật lại bảng
            xoaFrom();  // Xóa dữ liệu nhập
            if (cbbXuatXu != null) {
                cbbXuatXu.addItem(tenXX);  // Thêm vào danh sách
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi thêm xuất xứ: " + e.getMessage());
            e.printStackTrace(); // Hiển thị lỗi chi tiết trong console
        }
    }//GEN-LAST:event_btnThemXXActionPerformed

    private void btnSuaXXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaXXActionPerformed
      try {
            int chonRow = tblXuatXu.getSelectedRow();
            if (chonRow == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn Màu Sắc cần sửa!");
                return;
            }
            int id = Integer.parseInt(tblXuatXu.getValueAt(chonRow, 0).toString());
            String tenXX = txtXuatXu.getText();
            if (tenXX.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
                return;
            }
            if (tenXX.contains("  ")) {
                JOptionPane.showMessageDialog(this, "Họ tên không được chứa khoảng trắng liên tục.");
                return;
            }

            // Kiểm tra có chứa số không
            if (tenXX.matches(".*\\d.*")) {
                JOptionPane.showMessageDialog(this, "Tên không được chứa số.");
                return;
            }

            // Kiểm tra có chứa ký tự đặc biệt không (trừ dấu cách)
            if (!tenXX.matches("^[a-zA-ZàáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđÀÁẠẢÃÂẦẤẬẨẪĂẰẮẶẲẴÈÉẸẺẼÊỀẾỆỂỄÌÍỊỈĨÒÓỌỎÕÔỒỐỘỔỖƠỜỚỢỞỠÙÚỤỦŨƯỪỨỰỬỮỲÝỴỶỸĐ ]+$")) {
                JOptionPane.showMessageDialog(this, "Tên không được chứa ký tự đặc biệt.");
                return;
            }
            if(repoXX.checkTrung(tenXX)){
                JOptionPane.showMessageDialog(this, "Xuất Xứ đã tồn tại");
                return;
            }
            
            XuatXu xx = new XuatXu(id, tenXX);
            this.repoXX.update(xx);
            loadTable();
            xoaFrom();
            if (cbbXuatXu != null) {
                cbbXuatXu.addItem(tenXX);  // Thêm vào danh sách
            }
            

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi cập nhật thông tin xuất xứ! Vui lòng kiểm tra lại.");
        }
    }//GEN-LAST:event_btnSuaXXActionPerformed

    private void btnXoaXXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaXXActionPerformed
       try {
            int chonRow = tblXuatXu.getSelectedRow();
            if (chonRow == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn xuất xứ cần xóa!");
                return;
            }

            int id;
            try {
                id = Integer.parseInt(tblXuatXu.getValueAt(chonRow, 0).toString());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi: ID Chất Liệu không hợp lệ!");
                return;
            }

            // Xác nhận trước khi xóa
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Bạn có chắc chắn muốn xóa xuất xứ này?",
                    "Xác nhận xóa", JOptionPane.YES_NO_OPTION);

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            // Xóa nhân viên
            if (repoXX.delete(id)) {
                JOptionPane.showMessageDialog(this, "Xóa chất liệu thành công!");
                loadTable(); // Cập nhật lại bảng
                loadComboBoxChatLieu();
                xoaFrom();
                
            } else {
                JOptionPane.showMessageDialog(this, "Xóa xuất xứ thất bại! Vui lòng kiểm tra lại.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi hệ thống: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaXXActionPerformed

    private void tblXuatXuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblXuatXuMouseClicked
        try {
            int chon = tblXuatXu.getSelectedRow();
            if (chon != -1) {
                String id = tblXuatXu.getValueAt(chon, 0).toString();
                String tenXX = tblXuatXu.getValueAt(chon, 1).toString();

                txtID.setText(id);
                txtXuatXu.setText(tenXX);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblXuatXuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaXX;
    private javax.swing.JButton btnThemXX;
    private javax.swing.JButton btnXoaXX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblXuatXu;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtTimKiemXX;
    private javax.swing.JTextField txtXuatXu;
    // End of variables declaration//GEN-END:variables
}
